prometheus:
  nodeSelector:
    yandex.cloud/node-group-id: cate3fvh6rt2s7nez47k
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.158.160.135.8.nip.io
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  nodeSelector:
    yandex.cloud/node-group-id: cate3fvh6rt2s7nez47k
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.158.160.135.8.nip.io
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100